# Generated by Django 3.0.4 on 2020-03-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_auto_20200316_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'house', 'verbose_name_plural': 'houses'},
        ),
    ]
